spring: 
  cloud: 
    sentinel: 
      transport: 
        dashboard: 192.168.25.101:8087
      # sentinel nacos 规则持久化
      datasource: 
        ds: 
          nacos: 
            server-addr: 192.168.25.101:8848
            dataId: alibaba-nacos-feign-sentinel
            groupId: DEFAULT_GROUP
            rule-type: flow
            namespace: 